### ISSUE TITLE
get_blob_properties throws Faraday error when blob does not exist

### ISSUE THREAD

**Issue by andrews2** [Azure/azure-storage-ruby#120]
I noticed while using the get_blob_properties method that it doesn't error nicely with a BlobNotFound 404 like a general get_blob does. Instead it throws the error below, I included the backtrace from the point where our application calls the method:

```
undefined method `reason_phrase' for #<Faraday::Response:0x00000001860f78>
/usr/local/rvm/gems/ruby-2.3.1/gems/azure-core-0.1.14/lib/azure/core/http/http_response.rb:50:in `reason_phrase'
/usr/local/rvm/gems/ruby-2.3.1/gems/azure-core-0.1.14/lib/azure/core/http/http_error.rb:76:in `initialize'
/usr/local/rvm/gems/ruby-2.3.1/gems/azure-core-0.1.14/lib/azure/core/http/http_response.rb:74:in `new'
/usr/local/rvm/gems/ruby-2.3.1/gems/azure-core-0.1.14/lib/azure/core/http/http_response.rb:74:in `exception'
/usr/local/rvm/gems/ruby-2.3.1/gems/azure-core-0.1.14/lib/azure/core/http/http_request.rb:153:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/azure-core-0.1.14/lib/azure/core/http/signer_filter.rb:28:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/azure-core-0.1.14/lib/azure/core/http/signer_filter.rb:28:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/azure-core-0.1.14/lib/azure/core/http/http_request.rb:110:in `block in with_filter'
/usr/local/rvm/gems/ruby-2.3.1/gems/azure-core-0.1.14/lib/azure/core/service.rb:36:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/azure-core-0.1.14/lib/azure/core/filtered_service.rb:34:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/azure-core-0.1.14/lib/azure/core/signed_service.rb:41:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/azure-storage-common-1.0.1/lib/azure/storage/common/service/storage_service.rb:60:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/azure-storage-blob-1.0.1/lib/azure/storage/blob/blob_service.rb:176:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/azure-storage-blob-1.0.1/lib/azure/storage/blob/blob.rb:169:in `get_blob_properties'
```

**Comment by katmsft** [comment]
Hi, thanks for reporting the issue.

I have tried getting properties from a blob that does not exist, but gets BlobNotFound 404 error.

```
Azure::Core::Http::HTTPError:         Azure::Core::Http::HTTPError: Unknown (404): The specified blob does not exist.
            C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/azure-core-0.1.14/lib/azure/core/http/http_request.rb:153:in `call'
            C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/azure-core-0.1.14/lib/azure/core/http/signer_filter.rb:28:in `call'
            C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/azure-core-0.1.14/lib/azure/core/http/signer_filter.rb:28:in `call'
            C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/azure-core-0.1.14/lib/azure/core/http/http_request.rb:110:in `block in with_filter'
            C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/azure-core-0.1.14/lib/azure/core/service.rb:36:in `call'
            C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/azure-core-0.1.14/lib/azure/core/filtered_service.rb:34:in `call'
            C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/azure-core-0.1.14/lib/azure/core/signed_service.rb:41:in `call'
            E:/dev/src/ruby/azure-storage-ruby/common/lib/azure/storage/common/service/storage_service.rb:60:in `call'
            E:/dev/src/ruby/azure-storage-ruby/blob/lib/azure/storage/blob/blob_service.rb:176:in `call'
            E:/dev/src/ruby/azure-storage-ruby/blob/lib/azure/storage/blob/blob.rb:169:in `get_blob_properties'
            ./test/integration/blob/blob_properties_test.rb:78:in `block (3 levels) in <main>'
```

**Comment by yaxia** [comment]
`reason_phase` was added by Faraday in [0.10.0](https://github.com/lostisland/faraday/commit/a38ba7a13bc7ac2ba28c40604aa76303447f5d38). So could it be the old Faraday version in the environment?
