### ISSUE TITLE
Faraday::ConnectionFailed: Broken pipe

### ISSUE THREAD

**Issue by JohnLegrand** [Azure/azure-storage-ruby#144]
Attempting to write a 2GB zip file results in this error. 

This is my initialize: 
`@file_service = Azure::Storage::File::FileService.create(storage_account_name: ENV['AZURE_STORAGE_ACCOUNT'],
                                                                 storage_access_key: ENV['AZURE_STORAGE_ACCESS_KEY'])
        @file_service.with_filter(Azure::Storage::Common::Core::Filter::ExponentialRetryPolicyFilter.new)`

This is my method to send it: 

`def store_file(file_path, file_name, share, directory, content_type)
      content = ::File.open(file_path, 'rb') {|file| file.read}
      file = @file_service.create_file(share, directory, file_name, content.size, {:content_type => content_type})
      @file_service.put_file_range(share, directory, file.name, 0, content.size - 1, content)
    end`

this is the error:

2019-04-17T21:39:16.784Z 38078 TID-owcqf3yp4 WARN: Faraday::ConnectionFailed: Broken pipe
2019-04-17T21:39:16.784Z 38078 TID-owcqf3yp4 WARN: /Users/johnrichards/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/openssl/buffering.rb:324:in `syswrite'
/Users/johnrichards/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/openssl/buffering.rb:324:in `do_write'
/Users/johnrichards/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/openssl/buffering.rb:342:in `write'
/Users/johnrichards/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/protocol.rb:229:in `write0'
/Users/johnrichards/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/protocol.rb:203:in `block in write'
/Users/johnrichards/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/protocol.rb:220:in `writing'
/Users/johnrichards/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/protocol.rb:202:in `write'
/Users/johnrichards/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http/generic_request.rb:188:in `send_request_with_body'
/Users/johnrichards/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http/generic_request.rb:121:in `exec'
/Users/johnrichards/.rvm/gems/ruby-2.4.0/gems/aws-sdk-v1-1.66.0/lib/aws/core/http/patch.rb:27:in `block in new_transport_request'
/Users/johnrichards/.rvm/gems/ruby-2.4.0/gems/aws-sdk-v1-1.66.0/lib/aws/core/http/patch.rb:26:in `catch'
/Users/johnrichards/.rvm/gems/ruby-2.4.0/gems/aws-sdk-v1-1.66.0/lib/aws/core/http/patch.rb:26:in `new_transport_request'
/Users/johnrichards/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:1416:in `request'

**Comment by katmsft** [comment]
It seems that this error should be retried because this is intermittent error. Can you share if this issue can always be triggered or if this issue happens from time to time?

Retrying 'Faraday::ConnectionFailed: Broken pipe' will be added to our backlog.
