### ISSUE TITLE
Unable to send large files via #create_block_blob

### ISSUE THREAD

**Issue by rtyler** [Azure/azure-storage-ruby#62]
When attempting to send a large (50MB+) file, things don't quite work :(

```
/home/tyler/.rvm/gems/ruby-2.2.0/gems/azure-core-0.1.5/lib/azure/core/http/http_request.rb:147:in `call': RequestBodyTooLarge (413): The request body is too large and exceeds the maximum permissible limit. (Azure::Core::Http::HTTPError)
RequestId:7c1c2e38-0001-00ad-36b4-38a130000000
Time:2016-11-07T05:06:18.1887668Z
        from /home/tyler/.rvm/gems/ruby-2.2.0/gems/azure-core-0.1.5/lib/azure/core/http/signer_filter.rb:28:in `call'
        from /home/tyler/.rvm/gems/ruby-2.2.0/gems/azure-core-0.1.5/lib/azure/core/http/signer_filter.rb:28:in `call'
        from /home/tyler/.rvm/gems/ruby-2.2.0/gems/azure-core-0.1.5/lib/azure/core/http/http_request.rb:104:in `block in with_filter'
        from /home/tyler/.rvm/gems/ruby-2.2.0/gems/azure-core-0.1.5/lib/azure/core/service.rb:36:in `call'
        from /home/tyler/.rvm/gems/ruby-2.2.0/gems/azure-core-0.1.5/lib/azure/core/filtered_service.rb:34:in `call'
        from /home/tyler/.rvm/gems/ruby-2.2.0/gems/azure-core-0.1.5/lib/azure/core/signed_service.rb:41:in `call'
        from /home/tyler/.rvm/gems/ruby-2.2.0/gems/azure-storage-0.11.3.preview/lib/azure/storage/service/storage_service.rb:52:in `call'
        from /home/tyler/.rvm/gems/ruby-2.2.0/gems/azure-storage-0.11.3.preview/lib/azure/storage/blob/blob_service.rb:59:in `call'
        from /home/tyler/.rvm/gems/ruby-2.2.0/gems/azure-storage-0.11.3.preview/lib/azure/storage/blob/block.rb:114:in `create_block_blob'
        from blob-sync:50:in `block (2 levels) in <main>'
        from /home/tyler/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/set.rb:283:in `each_key'
        from /home/tyler/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/set.rb:283:in `each'
        from blob-sync:45:in `block in <main>'
        from blob-sync:17:in `each'
        from blob-sync:17:in `<main>'
```

**Comment by yaxia** [comment]
@rtyler Thanks for your feedback. It is by-design so far. Inside the SDK, it calls the [Azure Storage REST API](https://msdn.microsoft.com/en-us/library/azure/dd179451.aspx) with maximum size 64MB. We have issue #15 to track it and will support it later.
