### ISSUE TITLE
Singing key error

### ISSUE THREAD

**Issue by micahasmith** [Azure/azure-storage-ruby#63]
using azure lib 0.7.6

```
/Users/micahsmith/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/azure-core-0.1.5/lib/azure/core/auth/signer.rb:32:in `initialize': Signing key must be provided (Argume
ntError)
        from /Users/micahsmith/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/azure-core-0.1.5/lib/azure/core/auth/shared_key.rb:33:in `initialize'
        from /Users/micahsmith/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/azure-storage-0.11.3.preview/lib/azure/storage/blob/blob_service.rb:43:in `new'
        from /Users/micahsmith/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/azure-storage-0.11.3.preview/lib/azure/storage/blob/blob_service.rb:43:in `initialize'
        from upload.rb:12:in `new'
        from upload.rb:12:in `<main>'
```

and the following code:

```rb
client = Azure::Storage::Client.create(:storage_account_name => accountName, :storage_access_key => storageKey)

## throws here
@blobs = Azure::Storage::Blob::BlobService.new
```

**Comment by micahasmith** [comment]
fixed it with 

```rb
options = { :client => client }
@blobs = Azure::Storage::Blob::BlobService.new options 
```
