### ISSUE TITLE
Connection reset by peer exception after getting blobs for a period of time

### ISSUE THREAD

**Issue by xiaomi7732** [Azure/azure-storage-ruby#90]
I have logic to keep reading blobs. Something like:

## repeat the following code every 5 seconds
``` ruby
blob, content = @azure_blob.get_blob(@container, blob_name, {:start_range=>start_index} )
```
After the code ran for about 24 hours, I got the following exception:

```ruby
["org/jruby/ext/openssl/SSLSocket.java:809:in `sysread_nonblock'", 
"/usr/share/logstash/vendor/jruby/lib/ruby/shared/jopenssl19/openssl/buffering.rb:174:in `read_nonblock'", 
"/usr/share/logstash/vendor/jruby/lib/ruby/1.9/net/protocol.rb:141:in `rbuf_fill'", 
"/usr/share/logstash/vendor/jruby/lib/ruby/1.9/net/protocol.rb:92:in `read'", 
"/usr/share/logstash/vendor/jruby/lib/ruby/1.9/net/http.rb:2764:in `read_body_0'", 
"/usr/share/logstash/vendor/jruby/lib/ruby/1.9/net/http.rb:2719:in `read_body'", 
"/usr/share/logstash/vendor/jruby/lib/ruby/1.9/net/http.rb:1052:in `get'", 
"/usr/share/logstash/vendor/jruby/lib/ruby/1.9/net/http.rb:1331:in `transport_request'", 
"/usr/share/logstash/vendor/jruby/lib/ruby/1.9/net/http.rb:2680:in `reading_body'", 
"/usr/share/logstash/vendor/jruby/lib/ruby/1.9/net/http.rb:2679:in `reading_body'", 
"/usr/share/logstash/vendor/jruby/lib/ruby/1.9/net/http.rb:1330:in `transport_request'", 
"org/jruby/RubyKernel.java:1242:in `catch'", 
"/usr/share/logstash/vendor/jruby/lib/ruby/1.9/net/http.rb:1325:in `transport_request'", 
"/usr/share/logstash/vendor/jruby/lib/ruby/1.9/net/http.rb:1302:in `request'", "
"/usr/share/logstash/vendor/jruby/lib/ruby/1.9/net/http.rb:1295:in `request'", 
"/usr/share/logstash/vendor/jruby/lib/ruby/1.9/net/http.rb:746:in `start'", 
"/usr/share/logstash/vendor/jruby/lib/ruby/1.9/net/http.rb:744:in `start'", 
"/usr/share/logstash/vendor/jruby/lib/ruby/1.9/net/http.rb:1293:in `request'", 
"/usr/share/logstash/vendor/jruby/lib/ruby/1.9/net/http.rb:1035:in `get'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:80:in `perform_request'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `call'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response/follow_redirects.rb:78:in `perform_with_redirection'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response/follow_redirects.rb:66:in `call'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/azure-core-0.1.8/lib/azure/http_response_helper.rb:27:in `set_up_response'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/azure-core-0.1.8/lib/azure/core/http/http_request.rb:143:in `call'", 
"org/jruby/RubyMethod.java:116:in `call'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/azure-core-0.1.8/lib/azure/core/http/retry_policy.rb:41:in `call'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/azure-core-0.1.8/lib/azure/core/http/http_request.rb:104:in `with_filter'", 
"org/jruby/RubyMethod.java:116:in `call'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/azure-core-0.1.8/lib/azure/core/http/signer_filter.rb:28:in `call'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/azure-core-0.1.8/lib/azure/core/http/http_request.rb:104:in `with_filter'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/azure-core-0.1.8/lib/azure/core/service.rb:36:in `call'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/azure-core-0.1.8/lib/azure/core/filtered_service.rb:34:in `call'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/azure-core-0.1.8/lib/azure/core/signed_service.rb:41:in `call'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/azure-storage-0.11.4.preview/lib/azure/storage/service/storage_service.rb:52:in `call'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/azure-storage-0.11.4.preview/lib/azure/storage/blob/blob_service.rb:59:in `call'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/azure-storage-**0.11.4.preview/lib/azure/storage/blob/blob.rb:91:in `get_blob'",** 
"/usr/share/logstash/vendor/local_gems/950703aa/logstash-input-azureblob-0.9.8/lib/logstash/inputs/azureblob.rb:100:in `process'", 
"/usr/share/logstash/vendor/local_gems/950703aa/logstash-input-azureblob-0.9.8/lib/logstash/inputs/azureblob.rb:95:in `process'", 
"/usr/share/logstash/vendor/local_gems/950703aa/logstash-input-azureblob-0.9.8/lib/logstash/inputs/azureblob.rb:76:in `run'", 
"/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:456:in `inputworker'", 
"/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:449:in `start_input'"] {:exception=>#<IOError: Connection reset by peer>}
[2017-07-23T23:57:12,818][ERROR][logstash.inputs.logstashinputazureblob] Oh My, An error occurred.
```

Is this a SDK bug? Or is there anything I should do as caller to flush the buffer or something? Please let me know if more info is needed.

**Comment by xiaomi7732** [comment]
Look into the issue more, this is lead to because there is a appending blob in the storage which has big number of blocks. Since this is not related to the client, I'll close this thread.
Details reference: https://github.com/Azure/azure-storage-net/issues/267
