### ISSUE TITLE
get_blob_properties is hung when the vhd is being copied

### ISSUE THREAD

**Issue by puneetloya** [Azure/azure-storage-ruby#93]
I am copying a vhd from one subscription to the other. 

x = copy_blob_from_uri( 'container',  'vhd_name', source_uri)

blob = blob_client.get_blob_properties('container', 'vhd_name')
The timeout I get is:

```
/Users/john_doe/.rbenv/versions/2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize': execution expired (Faraday::ConnectionFailed)
	from /Users/john_doe/.rbenv/versions/2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'
	from /Users/john_doe/.rbenv/versions/2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'
	from /Users/john_doe/.rbenv/versions/2.2.3/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'
	from /Users/john_doe/.rbenv/versions/2.2.3/lib/ruby/2.2.0/timeout.rb:98:in `call'
	from /Users/john_doe/.rbenv/versions/2.2.3/lib/ruby/2.2.0/timeout.rb:98:in `timeout'
	from /Users/john_doe/.rbenv/versions/2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'
	from /Users/john_doe/.rbenv/versions/2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
	from /Users/john_doe/.rbenv/versions/2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'
	from /Users/john_doe/.rbenv/versions/2.2.3/lib/ruby/2.2.0/net/http.rb:1375:in `request'
	from /Users/john_doe/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:82:in `perform_request'
	from /Users/john_doe/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
	from /Users/john_doe/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
	from /Users/john_doe/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
	from /Users/john_doe/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response/follow_redirects.rb:78:in `perform_with_redirection'
	from /Users/john_doe/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response/follow_redirects.rb:66:in `call'
	from /Users/john_doe/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Users/john_doe/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /Users/john_doe/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/azure-core-0.1.8/lib/azure/http_response_helper.rb:27:in `set_up_response'
	from /Users/john_doe/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/azure-core-0.1.8/lib/azure/core/http/http_request.rb:143:in `call'
	from /Users/john_doe/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/azure-core-0.1.8/lib/azure/core/http/signer_filter.rb:28:in `call'
	from /Users/john_doe/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/azure-core-0.1.8/lib/azure/core/http/signer_filter.rb:28:in `call'
	from /Users/john_doe/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/azure-core-0.1.8/lib/azure/core/http/http_request.rb:104:in `block in with_filter'
	from /Users/john_doe/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/azure-core-0.1.8/lib/azure/core/service.rb:36:in `call'
	from /Users/john_doe/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/azure-core-0.1.8/lib/azure/core/filtered_service.rb:34:in `call'
	from /Users/john_doe/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/azure-core-0.1.8/lib/azure/core/signed_service.rb:41:in `call'
	from /Users/john_doe/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/azure-storage-0.12.1.preview/lib/azure/storage/service/storage_service.rb:53:in `call'
	from /Users/john_doe/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/azure-storage-0.12.1.preview/lib/azure/storage/blob/blob_service.rb:59:in `call'
```

**Comment by katmsft** [comment]
Looks like a connection issue instead of Client library issue. Can you reproduce this case firmly?
